# name: Deploy to Render

# on:
#   push:
#     branches:
#       - main  

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.11 

#     - name: Install dependencies
#       run: pip install -r requirements.txt  
      
#     - name: Re-train model on every push
#       run: python retrain.py  
    
#     - name: Test model on custom inputs
#       run: pytest -p no:cacheprovider --disable-warnings

#     - name: Build Docker image
#       run: |
#         docker build -t superstore_sales_predictor:latest .
#         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#         docker tag superstore_sales_predictor:latest sayam2801/superstore_sales_predictor:latest
#         docker push sayam2801/superstore_sales_predictor:latest

#     - name: Deploy to Render
#       run: |
#         curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
#           -H "Content-Type: application/json" \
#           --data '{
#             "image": "superstore_sales_predictor:latest",
#             "serviceId": "dep-cmv9luev3ddc73brjf50"  
#           }' \
#           https://api.render.com/v1/deploys

name: Deploy to Azure Web App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11 

    - name: Install dependencies
      run: pip install -r requirements.txt  
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build the Docker image
      run: docker build . -t superstore-sales-predictor:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag superstore-sales-predictor:latest ${{ secrets.DOCKER_USERNAME }}/superstore-sales-predictor:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/superstore-sales-predictor:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Azure Web App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
        images: ${{ secrets.DOCKER_USERNAME }}/superstore-sales-predictor:latest