name: Deploy to Render

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11 

    - name: Install dependencies
      run: pip install -r requirements.txt  
      
    - name: Build Docker image
      run: |
        docker build -t superstore_sales_predictor:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag superstore_sales_predictor:latest sayam2801/superstore_sales_predictor:latest
        docker push sayam2801/superstore_sales_predictor:latest

    - name: Deploy to Render
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "image": "superstore_sales_predictor:latest",
            "serviceId": "dep-cmv9luev3ddc73brjf50"  
          }' \
          https://api.render.com/v1/deploys